# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ej1' do

end

target 'ej1' do
  pod 'resizable-navigation-bar', '~> 1.0'
end